
```{r setup, include=FALSE}
# This chunk sets up global options for all code chunks.
knitr::opts_chunk$set(echo = TRUE, results = 'output')
```

```{r }
# Question Descriptive Statistics

# import data csv
data <- read.csv("./deaths.csv")
```

```{r }
# Five-number summary
summary(data$dm_prev_adj)
summary(data$Stroke_Death_Rate_Per_100000)
```
```{r }
# Histograms
hist(data$dm_prev_adj, main="Histogram of Diagnosed Diabetes Percentage", xlab="Diagnosed Diabetes Percentage")
hist(data$Stroke_Death_Rate_Per_100000, main="Histogram of Stroke Death Rate per 100,000", xlab="Stroke Death Rate per 100,000")
```

``` {r }
# Scatter
plot(data$dm_prev_adj, data$Stroke_Death_Rate_Per_100000, main="Scatterplot of Stroke Death Rate vs Diagnosed Diabetes Percentage", xlab="Diagnosed Diabetes Percentage", ylab="Stroke Death Rate per 100,000")
```

```{r }
# Selecting numeric variables
numeric_data <- data[, sapply(data, is.numeric)]
```

```{r }
# Correlation matrix
cor_matrix <- cor(numeric_data)
```

```{r }
# Correlation of all variables with Stroke_Death_Rate_Per_100000
cor_matrix["Stroke_Death_Rate_Per_100000",]
```

```{r }
# To identify multicollinearity
eigenvalues <- eigen(cor_matrix)$values
if(any(eigenvalues < 0.01)){
  print("Possible multicollinearity detected")
}
```





## Regression Models


# QUIZ2: Regression Models 
# SLR MODEL
``` {r }
# Read data
data <- read.csv("C:/Users/lloyd/Documents/GitHub/rproject/rproject/deaths.csv")
```

```{r }
# Model 1
model1 <- lm(Stroke_Death_Rate_Per_100000 ~ dm_prev_adj, data=data)
summary(model1)
```

# Model 2 (MLR):
```{R}
model2 <- lm(Stroke_Death_Rate_Per_100000 ~ dm_prev_adj + no_hsdip + ob_prev_adj, data=data)
summary(model2)
```

```{r }
# comparison on models
library(car)
vif(model2)
```







# LAST QUIZ

```{r}
model <- lm(Stroke_Death_Rate_Per_100000 ~ dm_prev_adj + home_val + female_hd, data=data)
summary(model)
```

```{r }
new_data <- data.frame(dm_prev_adj=7.4, home_val=85.5, female_hd=23.9)
prediction <- predict(model, newdata=new_data)
print(prediction)
```
















